
int timer    = 60; 

void setup() {
  pinMode(15, OUTPUT);
  pinMode(2, OUTPUT);
  pinMode(0, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(16, OUTPUT);
  pinMode(17, OUTPUT);
  pinMode(5, OUTPUT);
  pinMode(18, OUTPUT);
  pinMode(19, OUTPUT);
  pinMode(21, OUTPUT);
  pinMode(3, OUTPUT);
  pinMode(1, OUTPUT);
  pinMode(22, OUTPUT);
  pinMode(23, OUTPUT);
  pinMode(13, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(14, OUTPUT);
  pinMode(27, OUTPUT);
  pinMode(26, OUTPUT);
  pinMode(25, OUTPUT);
  pinMode(33, OUTPUT);
  pinMode(32, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(15, HIGH);   
  delay(timer);        
  digitalWrite(2, HIGH);   
  delay(timer); 
  digitalWrite(0, HIGH);   
  delay(timer);
  digitalWrite(4, HIGH);   
  delay(timer);      
  digitalWrite(16, HIGH);   
  delay(timer);
  digitalWrite(17, HIGH);   
  delay(timer);  
  digitalWrite(5, HIGH);   
  delay(timer);
  digitalWrite(18, HIGH);   
  delay(timer);    
  digitalWrite(19, HIGH);   
  delay(timer);
  digitalWrite(21, HIGH);   
  delay(timer);      
  digitalWrite(3, HIGH);   
  delay(timer);
  digitalWrite(1, HIGH);   
  delay(timer);    
  digitalWrite(22, HIGH);   
  delay(timer);
  digitalWrite(23, HIGH);   
  delay(timer);      
  digitalWrite(13, HIGH);   
  delay(timer);
  digitalWrite(12, HIGH);   
  delay(timer);      
  digitalWrite(14, HIGH);   
  delay(timer);
  digitalWrite(27, HIGH);   
  delay(timer);     
  digitalWrite(26, HIGH);   
  delay(timer);
  digitalWrite(25, HIGH);   
  delay(timer);
  digitalWrite(35, HIGH);   
  delay(timer);    
  digitalWrite(33, HIGH);   
  delay(timer);
  digitalWrite(32, HIGH);   
  delay(timer);    
    
  digitalWrite(32, LOW);    
  delay(timer); 
  digitalWrite(33, LOW);    
  delay(timer);    
  digitalWrite(35, LOW);    
  delay(timer); 
  digitalWrite(25, LOW);    
  delay(timer);    
  digitalWrite(26, LOW);    
  delay(timer);    
  digitalWrite(27, LOW);    
  delay(timer); 
  digitalWrite(14, LOW);    
  delay(timer);    
  digitalWrite(12, LOW);    
  delay(timer); 
  digitalWrite(13, LOW);    
  delay(timer);     
  digitalWrite(23, LOW);    
  delay(timer); 
  digitalWrite(22, LOW);    
  delay(timer);   
  digitalWrite(1, LOW);    
  delay(timer); 
  digitalWrite(3, LOW);    
  delay(timer);  
  digitalWrite(21, LOW);    
  delay(timer); 
  digitalWrite(19, LOW);    
  delay(timer);    
  digitalWrite(18, LOW);    
  delay(timer); 
  digitalWrite(5, LOW);    
  delay(timer);               
  digitalWrite(17, LOW);    
  delay(timer); 
  digitalWrite(16, LOW);    
  delay(timer);    
  digitalWrite(4, LOW);    
  delay(timer); 
  digitalWrite(0, LOW);    
  delay(timer);    
  digitalWrite(2, LOW);    
  delay(timer);   
  digitalWrite(15, LOW);    
  delay(timer);               
}
